TecharoHQ/anubis

CHANGELOG.md, README.md
- Manual testing on git.xeserv.us if required
This is a documentation change, no testing required.
=> README: point to techarohq GHCR repo

cmd/anubis/index.templ, cmd/anubis/index_templ.go, docs/docs/CHANGELOG.md, docs/docs/user/_category_.json, docs/docs/user/known-broken-extensions.md, docs/docs/user/why-see-challenge.md
Closes #25
Closes #38
Also includes the beginnings of a "user guides" section in the docs for user-facing documentation.
Checklist:
=> cmd/anubis: explain why users are seeing Anubis

cmd/anubis/main.go
Also:
* check parse error
* require strict base64 decoding
* ignore always nil sha256sum error to simplify codeflow
Checklist:
=> cmd/anubis: use golang-jwt to check expiry date

.github/workflows/docker-pr.yml, cmd/containerbuild/main.go
Closes #65
Pull request images will now be `ttl.sh/techaro/pr-{number}/anubis:24h`.
Checklist:
=> Fix docker image CI for pull requests

README.md
Title says it does, noticed it broke 😢
I didn't add a changelog entry because this feels like it doesn't need one.
Checklist:
=> docs(README): fix mascot link

.github/workflows/go.yml, cmd/anubis/main.go, cmd/containerbuild/main.go, internal/headers.go, internal/test/playwright_test.go
Thanks for making staticcheck @dominikh!
=> Add staticheck to CI

cmd/anubis/main.go, decaymap/decaymap.go, decaymap/decaymap_test.go, docs/docs/CHANGELOG.md, lib/anubis.go
=> Add periodic cleanup job for DecayMap (#8)

README.md
=> chore: Update readme to reflect refactor from the monorepo

PULL_REQUEST_TEMPLATE.md, docs/docs/CHANGELOG.md, internal/test/playwright_test.go
see https://github.com/TecharoHQ/anubis/pull/133#issuecomment-2764733687
Checklist:
=> fix(tests): disable integration tests on Windows

docs/docs/CHANGELOG.md, internal/test/playwright_test.go, web/js/proof-of-work.mjs
This PR fixes a couple minor typos.
Checklist:
=> various: fix minor typos

.github/workflows/docker-pr.yml, .github/workflows/docker.yml, .github/workflows/docs-deploy.yml, .github/workflows/go.yml, docs/docs/CHANGELOG.md
This PR fixes most findings by `zizmor`. Leaving as draft until https://github.com/TecharoHQ/anubis/pull/188 is merged.
Checklist:
=> workflows: fix zizmor findings (part 1)

docs/docs/CHANGELOG.md, web/index.templ, web/index_templ.go
=> web: add noindex to base HTML template

.github/workflows/go.yml, package.json
=> package.json: fix build command

docs/docs/user/known-instances.md
Adds some big names like the UN and the additional linux pages (lore.)
Checklist:
=> feat(docs): expand known instances list with new entries 

docs/docs/user/known-instances.md
Remove the duplicate scioly.org mention.
Checklist:
=> docs/docs/user/known-instances.md: remove duplicate scioly.org mention

docs/docs/user/known-instances.md
Changed some spacing and capitalization to make more sense. Also updated my site entry since the list changes.
Checklist:
=> feat(docs): grammar fixes & updates for known users

.github/workflows/docker-pr.yml, .github/workflows/docker.yml, .github/workflows/docs-deploy.yml, .github/workflows/go.yml, .github/workflows/package-builds-stable.yml, .github/workflows/package-builds-unstable.yml, .github/workflows/zizmor.yml
Mostly an experiment to see if it makes CI faster.
=> use depot builders

docs/src/css/custom.css
Based on an issue by Xe
Checklist:
=> Docs pallete fix

web/index.templ, xess/xess.go
Using outline shorthand *saves 36 bytes*
Checklist:
=> Use outline shorthand 

docs/docs/user/known-instances.md
=> Add Haiku to known instances

docs/docs/CHANGELOG.md, docs/docs/user/known-instances.md
This change is adding git.lupancham.net to the list of known instances of use
Checklist:
=> added an another git.lupancham.net to known instances of use

docs/docs/CHANGELOG.md, docs/docs/admin/environments/traefik.mdx, docs/docs/admin/installation.mdx
Added Information on how to connect Anubis with Traefik in its current state
This work is partially based on: #176 
Im stealing it as suggested by its author: https://github.com/TecharoHQ/anubis/pull/176#issuecomment-2799018036
Checklist:
=> feat(docs): added info on how to configure traefik

docs/docs/CHANGELOG.md
Also fixed a typo in 1.14.0's release 
Checklist:
=> docs: Update changelog with consistent periods

cmd/anubis/main.go, docs/docs/CHANGELOG.md, lib/anubis.go, lib/policy/bot.go, lib/policy/checker.go, lib/policy/checker_test.go, lib/policy/checkresult.go, lib/policy/policy.go
=> feat(lib): use Checker type instead of ad-hoc logic

data/botPolicies.json, data/botPolicies.yaml, docs/docs/CHANGELOG.md, docs/docs/admin/policies.mdx
=> data: disable generic-bot-catchall by default

docs/docs/user/known-instances.md
=> chore(known-instances): Add https://git.devuan.org/

cmd/anubis/main.go, cmd/containerbuild/main.go, docs/docs/CHANGELOG.md, internal/headers.go, internal/ogtags/fetch.go, internal/test/playwright_test.go, lib/anubis.go, lib/policy/policy.go
Closes #331 
Just some general nits / more through error handling so we never have to look at panics :) 
Checklist:
=> fix: improve error handling and create the json encoder once #331

.github/workflows/docs-test.yml, docs/docusaurus.config.ts, docs/src/css/custom.css
Closes #333
I'm very bad at design so I just picked colors that looked reasonable enough to me. Hopefully this will be enough to get us to the next stage!
=> fix(docs): make the docs respect light/dark mode

cmd/anubis/main.go, docs/docs/CHANGELOG.md, internal/headers.go
=> feat(cmd/anubis): compute full XFF header

docs/docs/CHANGELOG.md, web/index.templ, web/index_templ.go, xess/xess.css
Needed for BotStopper.
Checklist:
=> feat(xess): move CSS color definitions to CSS variables

docs/docs/CHANGELOG.md, docs/docs/admin/default-allow-behavior.mdx, docs/docs/admin/policies.mdx
=> Add documentation for default allow behavior

lib/anubis.go
This makes `PassChallenge` use the path from the url given in the `redir` form value of `/.within.website/x/cmd/anubis/api/pass-challenge`.
Otherwise, `r.URL.Path` was always `/.within.website/x/cmd/anubis/api/pass-challenge` and this didn't match the path checker rules correctly, which caused a failure when the difficulty mismatched (a 403 error page because the challenge doesn't match).
An easy way to reproduce the problem is with a `botPolicy.json` which uses a different difficulty on a path than another rule which would match if the path did not:
```yaml
{
"bots": [
{
"name": "custom-difficulty",
"path_regex": "^/$",
"action": "CHALLENGE",
"challenge": {
"difficulty": 3,
"report_as": 4
}
},
{
"name": "generic-browser",
"user_agent_regex": "Mozilla",
"action": "CHALLENGE",
"challenge": …
```
=> fix(lib): use correct URL for path checker in PassChallenge

README.md
Preview: https://github.com/luzpaz/anubis/blob/repology/README.md#packaging-status
Checklist:
=> README: represent repology badge in 3 column format

data/crawlers/mojeekbot.yaml, docs/docs/CHANGELOG.md
Update the User Agent regex in MojeekBot
Checklist:
=> Fix: mojeekbot regex

docs/docs/admin/environments/traefik.mdx
Just fixed two typos in the Traefik configuration.
=> Fix Traegik but funny typos

README.md, docs/docs/index.mdx
=> docs(README): enable dark mode for the star history view

docs/docs/admin/environments/traefik.mdx
- Fix wording to make more clear and fix typos in the`traefix.mdx` file
- Add fix for the `!NOTE` which was previously not rendering due to incorrect syntax
Checklist:
=> fix(docs): fix typos in Traefik integration docs

docs/docs/admin/installation.mdx
=> docs(install): note that Anubis needs certain paths proxied

anubis.go, cmd/anubis/main.go, docs/docs/CHANGELOG.md, docs/docs/admin/installation.mdx, internal/test/playwright_test.go, lib/anubis.go, lib/anubis_test.go, web/index.templ, web/index_templ.go, web/js/main.mjs, xess/xess.go, yeetfile.js
=> feat: add support for a base prefix

lib/policy/config/testdata/good/old_xesite.json
=> test(config): add Xesite's old policy file to known good test cases

go.mod, go.sum, internal/slog.go, lib/anubis.go, lib/config.go, lib/http.go
This PR is functionally identical besides for the change of a few log messages. No Logic was changed. 
Supersedes #378 
Checklist:
=> refactor(lib): Split up anubis.go into some smaller files. 

.github/workflows/package-builds-stable.yml, .github/workflows/package-builds-unstable.yml
One last thing before the release is cut!
=> ci(packages): final pre-release yeet bump

data/botPolicies.yaml, docs/docs/CHANGELOG.md, docs/docs/admin/configuration/custom-status-codes.mdx, lib/anubis.go, lib/anubis_test.go, lib/http.go, lib/policy/config/config.go, lib/policy/config/testdata/bad/status-codes-0.json, lib/policy/config/testdata/bad/status-codes-0.yaml, lib/policy/config/testdata/good/status-codes-paranoid.json, lib/policy/config/testdata/good/status-codes-paranoid.yaml, lib/policy/config/testdata/good/status-codes-rfc.json, lib/policy/config/testdata/good/status-codes-rfc.yaml, lib/policy/policy.go, lib/testdata/aggressive_403.yaml, test/anubis_configs/aggressive_403.yaml, test/unix-socket-xff/start.sh, test/unix-socket-xff/test.mjs
=> feat(config): add ability to customize HTTP status codes Anubis returns

docs/docs/user/known-instances.md
The FreeCAD forum is also using anubis
=> docs: Add FreeCAD Forum to list of known users

docs/docs/user/known-instances.md
Adding the websites from the ScummVM project that are now protected by Anubis to the list of known instances.
Thank you!
Checklist:
=> docs(known-instances): add ScummVM

docs/docs/user/known-instances.md
Update to #407 in accordance with https://blog.freecad.org/2025/04/30/forum-and-wiki-performance-anubis-deployed/
=> docs(known-instances): Add FreeCAD Wiki to known instances

data/botPolicies.json, data/botPolicies.yaml, data/bots/_deny-pathological.yaml, data/crawlers/_allow-good.yaml, data/embed.go, docs/docs/CHANGELOG.md, docs/docs/admin/configuration/import.mdx, lib/policy/config/config.go
Closes #398 
Known issue: this allows recursive imports.
Checklist:
=> feat(config): allow multi-level imports

docs/docs/admin/environments/caddy.mdx, test/caddy/Caddyfile, test/caddy/Dockerfile, test/caddy/docker-compose.yaml, test/caddy/start.sh
=> docs: add caddy docs

cmd/anubis/main.go, docs/docs/CHANGELOG.md
=> fix(anubis): disable opengraph passthru by default

docs/docs/CHANGELOG.md, web/static/img/ATTRIBUTIONS.txt
=> chore(static/img): add mascot attributions to the repo

cmd/anubis/main.go, docs/docs/CHANGELOG.md, docs/docs/admin/installation.mdx
=> feat: add TARGET_INSECURE_SKIP_VERIFY setting to allow self-signed HTTPS backends

docs/docs/CHANGELOG.md, lib/anubis.go
Closes #468
Checklist:
(did not run integration tests, will see if CI passes :) )
=> fix(jwt): update nonce value in challenge JWT cookie to be a string

.github/workflows/docker-pr.yml, .github/workflows/docker.yml, .github/workflows/docs-deploy.yml, .github/workflows/docs-test.yml
Prevents me from getting annoying emails everytime i push to my fork :( 
Checklist:
=> feat(ci): use dynamic repository owner and name in Docker actions

data/bots/irc-bots/archlinux-phrik.yaml
Tracks https://gitlab.archlinux.org/archlinux/infrastructure/-/merge_requests/950
=> fix(bots/phrik): add IPv6 address for phrik

.github/actions/spelling/expect.txt, docs/docs/admin/frameworks/_category_.json, docs/docs/admin/frameworks/htmx.mdx
Based on a workaround I made for tangled.sh
=> docs: add HTMX workaround

.github/actions/spelling/expect.txt, data/apps/qualys-ssl-labs.yml, data/apps/searx-checker.yml, docs/docs/CHANGELOG.md
Closes #505
Closes #504 
Checklist:
=> feat(apps): add SearXNG instance tracker policy and Qualys Labs SSL testing rules

.github/actions/spelling/expect.txt, .github/workflows/docs-deploy.yml
I'm moving clusters around so I need to move the docs to a new home.
=> chore(docs/deploy): move to new cluster

docs/docs/CHANGELOG.md, lib/policy/config/config.go, lib/policy/config/expressionorlist.go, lib/policy/config/expressionorlist_test.go
=> fix(expression): add validation for empty expression list in CEL

.github/actions/spelling/expect.txt, docs/docs/user/known-instances.md
=> add Weblate to known-instances.md

data/botPolicies.yaml, data/clients/x-firefox-ai.yaml, docs/docs/CHANGELOG.md
=> feat(data): add x-firefox-ai default challenge rule

docs/docs/CHANGELOG.md, yeetfile.js
=> feat(yeetfile): build GOARCH=ppc64le packages

docs/docs/user/known-instances.md
=> add my site to known-instances.md

.github/workflows/ssh-ci-runner-cron.yml, .github/workflows/ssh-ci.yml
https://github.com/JasonLovesDoggo/anubis/actions/runs/15595425215/job/43924619738
Prevents me from getting spammed by GHA. extends #487 
Checklist:
=>  fix(ci): conditionally run SSH jobs for TecharoHQ/anubis

docs/docs/user/known-instances.md
Dear Anubis Team,
Thank you very much for creating this excellent piece of software! Anubis is solving a problem that has been haunting our ReactOS website for at least the past 2 years.
It used to be possible to block rogue AI crawling bots via IP and User-Agent in the beginning. But they got more malicious in the last year and basically broke every rule that crawlers and websites happily agreed on for 20+ years -- regardless of the consequences for the open-source projects we all depend on.
I've deployed Anubis for all our affected services in the past few days. We finally took back control of our own website.
Thinking about writing a blog post later. But for now, let me add ourselves as proud customers, if that is of any help to you.
Best regards, also in the name of the ReactOS Team, …
=> Add ReactOS to known-instances.md

.github/actions/spelling/excludes.txt, .github/actions/spelling/expect.txt, lib/anubis_test.go, lib/config_test.go, lib/policy/config/asn_test.go, lib/policy/config/config.go, lib/policy/config/geoip.go, lib/policy/config/geoip_test.go, lib/policy/config/testdata/bad/threshold-challenge-without-challenge.yaml, lib/policy/config/testdata/bad/thresholds.yaml, lib/policy/config/threshold_test.go, lib/testdata/test_config.yaml
=> fix(config): actually load threshold config

data/botPolicies.yaml, docs/docs/CHANGELOG.md
Closes #700 
I don't know how I missed this in testing.
Checklist:
=> fix(default-config): off-by-one error in the default thresholds

.github/actions/spelling/excludes.txt, docs/docs/user/known-instances.md
Adding the sites from Duke University that are currently protected by Anubis, and coinhoards.org which is using Anubis as well.
The second commit adds my own project, so since it is a form of self-advertising, feel free to reject it.
Checklist:
=> docs(known-instances): Add Duke University, coinhoards.org (and myself) to known instances

docs/docs/user/known-instances.md
Daily update of the instances list!
This time: marginalia-search.com and the German institute of Forschungszentrum Jülich (they have the fastest super-computer in Europe btw)
Checklist:
=> docs(known-instances): update list of known instances

docs/docs/user/known-instances.md
Second one for the day: rpmfusion has Anubis too!
Checklist:
=> docs(known-instances): add rpmfusion.org and wiki.freepascal.org to known instances

.github/workflows/smoke-tests.yml, test/git-push/docker-compose.yaml, test/git-push/test.sh, test/git-push/var/.gitignore
=> test: add git push smoke test

docs/docs/CHANGELOG.md, lib/anubis.go, lib/http.go, web/index.go, web/index.templ, web/index_templ.go
Closes #659
Closes #832
Checklist:
=> fix: race conditions, cookie logic, and the try again button

lib/localization/locales/de.json, lib/localization/locales/en.json, lib/localization/locales/es.json, lib/localization/locales/et.json, lib/localization/locales/fil.json, lib/localization/locales/fr.json, lib/localization/locales/is.json, lib/localization/locales/it.json, lib/localization/locales/ja.json, lib/localization/locales/manifest.json, lib/localization/locales/pt-BR.json, lib/localization/locales/tr.json, lib/localization/locales/zh-CN.json, lib/localization/locales/zh-TW.json, lib/localization/localization_test.go, web/index.templ
=> fix(localization): fix missing string in template

docs/docs/CHANGELOG.md, docs/docs/admin/configuration/expressions.mdx, lib/policy/expressions/environment.go, lib/policy/expressions/environment_test.go
Also add tests to the bot expressions custom functions.
Checklist:
=> feat(expressions): add missingHeader function to bot environment

lib/anubis.go, lib/anubis_test.go, lib/http.go
=> fix(lib): add comprehensive XSS protection logic

docs/docs/CHANGELOG.md, lib/anubis.go, lib/http.go, web/index.go, web/index.templ, web/index_templ.go
=> fix(web): make the try again button always go back to /

data/bots/_deny-pathological.yaml, data/bots/custom-async-http-client.yaml, docs/docs/CHANGELOG.md
=> feat(default-rules): add weight to Custom-AsyncHttpClient

docs/docs/CHANGELOG.md, internal/log.go, lib/anubis.go, lib/challenge/challenge.go, lib/http.go
=> fix(anubis): store the challenge method in the store

docs/docs/CHANGELOG.md, internal/log.go, lib/anubis.go, lib/anubis_test.go, lib/config.go, lib/http.go
=> fix(lib): add the ability to set a custom slog Logger

docs/docs/user/known-instances.md
Checklist:
(not applicable, I believe?)
=> Add HackLab.TO to known instances

docs/docs/CHANGELOG.md, web/js/worker/sha256-purejs.mjs
=> fix(web/sha256-browserjs): fix function name

.github/workflows/docker-pr.yml, .github/workflows/docker.yml, .github/workflows/docs-deploy.yml, .github/workflows/docs-test.yml, .github/workflows/zizmor.yml
Reverts TecharoHQ/anubis#952
Whenever I merge, THEN it fails... YAY!
https://github.com/TecharoHQ/anubis/actions/runs/16766226996/job/47471827482
=> Revert "build(deps): bump the github-actions group with 2 updates"

docs/docs/admin/policies.mdx
Super simple docs fix to repair a broken link I spotted. No changes to code.
Checklist:
=> docs: Fix broken link

.github/PULL_REQUEST_TEMPLATE.md
=> docs: add reminder for verified signatures in PR template

.github/workflows/ssh-ci.yml, test/ssh-ci/rigging.sh
This runs CI against the raspi embedded into my tower's shellbox.
Checklist:
=> ci: add aarch64 for ssh CI

test/ssh-ci/rigging.sh
=> ci(ssh): don't print uname -av output
