TecharoHQ/anubis

.github/workflows/docker.yml
cmd/containerbuild/main.go

Closes #48
Default to using ttl.sh for contributions from outside the org, done via a simple needle/haystack member in list.
Checklist:

cmd/containerbuild: default to ttl.sh for third party contributions

---

cmd/anubis/internal/dnsbl/dnsbl_test.go

This allows the tests to succeed in a build sandbox with no internet raccess
Checklist:

Skip TestLookup test when networking is disabled

---

cmd/anubis/main.go
cmd/anubis/policy.go

hash.Write never returns error so removing it from the results simplifies usage and eliminates dead error handling.
Checklist:

cmd/anubis: do not return error from sha256

---

docs/docs/CHANGELOG.md
docs/docs/admin/installation.mdx

I had some issues when following the installation guide. The file `/data/cfg/botPolicy.json` is not used automatically. After debugging I found that it is indeed not the default value for the environment variable, so I clarified the documentation.
Also, in the example the `botPolicy.json` is mounted into the `nginx` container, not the `anubis-nginx`, so that could not have worked anyway.
Checklist:

fix: installation instructions and example

---

.gitignore

Removes `main` from the repo and updates `.gitignore` to help prevent accidents like this again. `.test` comes from go test binaries, which I feel is also worth excluding
Omitted changelog because this doesn't feel like it needs one!
Checklist:

chore: remove built binary and prevent accidental addition again

---

decaymap/decaymap.go
docs/docs/CHANGELOG.md
internal/test/playwright_test.go
lib/anubis.go
lib/policy/config/config.go
lib/policy/policy.go

I ran golangci-lint and applied some of the errors it reported. 
Some of the changes:
- Removal of nil check on `[]string`, as it is not a pointer, so always has a 0 value of empty.
- Using `Equal()` for time, instead of `==` to insure it is handled properly.
- Use `time.Until()` instead of doing the subtraction manually with time.now()
- Fix error handling while parsing and validation the config. We were setting the error, then moving the for-loop along, losing the error.
- Switched it to use a list, instead of `errors.Join` directly, so that it is more obvious what we are doing and not losing information prematurely.
- Excess noop err check.
Checklist:

Linting and staticcheck fixes.

---

docs/docs/CHANGELOG.md
docs/src/css/custom.css

If using dark mode, these lines are not legible at all. I separated the colors into variables and added more contrasting colors for the dark mode.
Example page affected: https://anubis.techaro.lol/docs/admin/caveats-gitea-forgejo
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
I did not spend too much time on the actual color values, just eyeballed them with the picker in devtools, feel free to suggest something nicer.
Checklist:

fix(docs): Make dark mode diff lines readable

---

docs/docs/admin/policies.md

This PR fixes the broken link to https://github.com/TecharoHQ/anubis/blob/main/data/botPolicies.json, possibly after work on #77. Found while reading the docs for random reading.
For the maintainer(s) and contributors, thank you for the work!

Fix broken link to default policy file

---

data/botPolicies.json
docs/docs/CHANGELOG.md

Closes #109
This was a hack I did on stream. I thought this would have a positive effect, but a combination of real-world testing from people using Anubis in prod and gray-hat testing has proven this is an unfeature and is probably causing more harm than good at this stage.
In the future I'll probably make the `dnsbl` block more flexible so that you can specify your own lists and rules around them.
Checklist:

data: disable DroneBL lookups by default

---

cmd/anubis/main.go
docs/docs/CHANGELOG.md
docs/docs/admin/installation.mdx
internal/headers.go
lib/anubis_test.go

This is just something that I had to first hack to make local testing work but I saw that the flag `debug-x-real-ip-default` existed later. But I still think that using the remote address is better than just using a fixed string that is passed on the command line or env.
This is something you can take or leave, it doesn't matter to me that much.
Checklist:

Change how to make Anubis work without a reverse proxy

---

docs/docs/CHANGELOG.md
internal/headers.go
lib/anubis.go

Demo: https://anubis.techaro.lol/.within.website/x/cmd/anubis/
Currently the embedded static content under the `/.within.website/x/cmd/anubis/` path on any Anubis-enabled site will serve all the content as browsable directories.
While the content itself is also accessible using normal means from the HTML code that loads the JavaScript files and images, for exmple, it is still an industry standard to disallow directory browsing on production websites, just to not give adversaries any possible hints as to what kinds of files are available on the server.
As it is now, the built-in `botPolicies.json` is also revealed in this listing. I'm not sure why it would even be necessary to have this data available on the client side? This PR does not address this issue, so the file will still be …

Hide directory browsing on the static content

---

docs/docs/developer/building-anubis.md
yeetfile.js

Provides directions that would have helped #153 be self-serving.

docs/developer: add build directions for manually building Anubis

---

docs/docs/CHANGELOG.md
web/index.templ
web/index_templ.go
web/js/main.mjs
web/js/proof-of-work-slow.mjs
web/js/proof-of-work.mjs

I found the spinner somewhat frustrating, since even though there's no truly accurate way to represent the time to complete a probabilistic process, the difficulty number doesn't give a very meaningful estimate of how long the user should expect to wait. This patch replaces the spinner with a progress bar based on how likely the user would've already completed the challenge. I think this provides a compromise for giving the idea of how long things _should_ take without actually saying how long things _will_ take.
For styling, I tried to match the overall aesthetic and picked colors xess already uses. I still think of it as somewhat temporary and expect it to be redesigned eventually. The performance impact added by having the worker threads report their status to the progress bar is …

Show a progress bar for the probability of completing the proof of work challenge

---

cmd/containerbuild/main.go
docs/docs/CHANGELOG.md

Using TrimRight will remove all characters from `*dockerRepo` from right to left that match a character contained on `"/"+filepath.Base(*dockerRepo)` (the cutset) until it doesn't matches anymore.
So for example, if `dockerRepo` is `example.com/fijxu/anubis`, and `"/"+filepath.Base(*dockerRepo)` is `/anubis`, it will remove `u/anubis` and not just `/anubis` from `dockerRepo` because `u` is a character inside the cutoff.
here is a small example if you want to try it before merging it:
```golang
package main
import "fmt"
import "strings"
import "path/filepath"
func main() {
dockerRepo := "example.com/fijxu/anubis"
koDockerRepo := strings.TrimSuffix(dockerRepo, "/"+filepath.Base(dockerRepo))
koDockerRepoSuffix := strings.TrimRight(dockerRepo, "/"+filepath.Base(dockerRepo)) …
```

cmd/containerbuild: Use TrimSuffix instead of TrimRight on containerbuild

---

.gitattributes
cmd/anubis/main.go
docs/docs/CHANGELOG.md
lib/anubis.go
lib/policy/config/config.go
web/build.sh
web/index.go
web/index.templ
web/index_templ.go
web/js/bench.mjs
web/js/main.mjs
web/js/proof-of-work-slow.mjs
web/js/proof-of-work.mjs

While developing #87, I made a benchmarking tool to check that I hadn't introduced any performance regressions. It's fairly basic, only measuring the time a challenge took vs the number of hashes it had to compute. It can also alternate between two algorithms and compare their speeds, but there's high variance between runs so it takes a while to converge on a good number. Huge amount of inline CSS to avoid shipping extra CSS on the non-benchmark pages, otherwise the templates would need a refactor.
Checklist:

Debug tool for benchmarking proof-of-work algorithms

---

docs/docs/CHANGELOG.md
web/build.sh

This will allow [LibreJS](https://www.gnu.org/software/librejs/) users to pass the captcha without having to whitelist Anubis manually.
I'm not sure if all the code used is MIT since it was taken from another sources, but is up to you @Xe
If you want me to make any changes, just tell me.
If you want to test it with LibreJS before merging it, you can test it by clicking any video on https://inv.nadeko.net or by pulling https://git.nadeko.net/Fijxu/-/packages/container/anubis/latest (https://git.nadeko.net/Fijxu/anubis-patches/actions/runs/23)
Checklist:

web/js: Add LibreJS banner to Anubis JavaScript to allow LibreJS users to run the challenge

---

cmd/anubis/main.go
docs/docs/CHANGELOG.md

closes #93 
Handle addresses that include a hostname, not just ports.  If the address starts with a colon, assume it's just a port and prefix it with "http://localhost".  Otherwise, prefix the entire address with "http://".  This ensures that the listener URL is correctly formatted regardless of whether it includes a hostname or just a port.
Checklist:

fix(logs): Correctly format listener address 

---

xess/xess.go

In `xess`, use `go tool ...` instead of `go run ...@latest` for `go:generate`.
When using the latter, generation of assets with the `-mod=vendor` flag fails. A notable example of this is with Nixpkgs' `buildGoModule`.
```
> @techaro/anubis@1.0.0-see-VERSION-file assets
> go generate ./... && ./web/build.sh && ./xess/build.sh
(✓) Complete [ updates=2 duration=3.625777ms ]
go: github.com/a-h/templ/cmd/templ@latest: cannot query module due to -mod=vendor
xess/xess.go:15: running "go": exit status 1
```
This PR removes `@latest` from the command, and changes `go run` to `go tool` to be consistent with other files.
Checklist:
- I don't think one is needed since this is a build-time fix and should not impact users.

xess: fix asset generation with `-mod=vendor`

---

docs/docs/CHANGELOG.md
lib/anubis.go

- Fixed a typo in the challenge page title, removing an unnecessary backslash.
- Updated the index page title to "Making sure you're not a bot!".
closes #171 
Checklist:

Fix: Correct typo in challenge page title (main)

---

cmd/anubis/main.go
docs/docs/CHANGELOG.md

Closes #182.
There doesn't look currently to be tests that cover `cmd/anubis` itself, so I haven't added a test for this. I have tested manually that it does what we expect.
Checklist:

cmd/anubis: support ED25519_PRIVATE_KEY_HEX_FILE

---

.github/workflows/zizmor.yml
docs/docs/CHANGELOG.md

This PR adds @woodruffw's [`zizmor`](https://github.com/woodruffw/zizmor) for static analysis of GitHub Actions workflows.
Checklist:

ci: add `zizmor`

---

.github/dependabot.yml
docs/docs/CHANGELOG.md

This PR enables Dependabot for GitHub Actions, Go, and npm on a weekly cadence.
Checklist:

dependabot: enable

---

Makefile
docs/docs/CHANGELOG.md
docs/docs/developer/building-anubis.md
package.json

Based on advice from IRC, a makefile helps downstream packagers understand how to build the software.
Checklist:

add a Makefile

---

cmd/anubis/main.go
docs/docs/CHANGELOG.md

cmd/anubis: add --extract-resources flag to extract static assets to the filesystem

---

Makefile
docs/docs/developer/building-anubis.md
go.mod
go.sum

Closes #226
Makefile dependencies are backwards, apparently.
Also add staticcheck as a `go tool` dependency and documentation on how to update Go when the system package manager isn't behaving properly.

Makefile: fix subtle logic bug

---

docs/docs/user/known-instances.md

I've been keeping a list in my head for a while, but I think a canonical location with most known instances could help others, e.g. for deciding wheather to use Anubis or not and to get in contact with Anubis operators.
Checklist:

docs/user/known-instances: add page

---

.github/workflows/package-builds-stable.yml
.github/workflows/package-builds-unstable.yml

Hash pins the workflows added in #194. I don't think this needs another CHANGELOG entry given we already have one for this work.
Checklist:

workflows: hash pin more Actions

---

cmd/containerbuild/main.go

Minor fix to the docker parsing of tags in the image reference to split at the last colon as per the docker spec[1]. This fixes container builds when the repository already contains an earlier colon, which is common when pushing to a local registry with a port, eg: `localhost:5000/org/name:latest`. The previous would be parsed with the repo as `localhost` and tag as `5000/org/name:latest`, which would cause the build to fail.
[1] https://docs.docker.com/reference/cli/docker/image/tag/#description
Checklist:

cmd/containerbuild/main.go: fix docker tag parsing

---

docs/docs/CHANGELOG.md
internal/ogtags/cache.go
internal/ogtags/fetch.go
internal/test/playwright_test.go
lib/anubis_test.go

In the past, you could get logs like ```
{"time":"2025-04-11T18:53:02.39479254Z","level":"ERROR","source":{"function":"github.com/TecharoHQ/anubis/lib.(*Server).RenderIndex","file":"github.com/TecharoHQ/anubis/lib/anubis.go","line":346},"msg":"failed to get OG tags","err":"unsupported Content-Type: image/png"}
``` 
Miss-leading a user that there is an actual error when it's just debug worthy. This PR fixes that along with some other minute changes
also see https://ptb.discord.com/channels/1191183827591241828/1330297062587371602/1360334215748649131 
Checklist:

fix(fetch): improve error handling for Content-Type parsing

---

docs/docs/CHANGELOG.md
run/anubis.freebsd

I have added an rc.d script for FreeBSD so Anubis can be run as a daemon.
Typically, this file would be copied to `/usr/local/etc/rc.d` and variables set in `/etc/rc.conf` (i.e. to enable it, and set the environment file).
Tested and running well on my Forgejo Instance - https://forge.notnull.space/
Checklist:

Create Anubis FreeBSD rc.d script

---

docs/docs/CHANGELOG.md
go.mod
lib/anubis.go
web/index.go
web/index.templ
web/index_templ.go
web/js/main.mjs

Embedding the challenge data in the initial HTML response saves an extra HTTP roundtrip and allows the browser to start working on the challenge immediately.
Checklist:

perf: embed challenge data in HTML

---

docs/docs/CHANGELOG.md
lib/anubis.go
lib/policy/bot.go
lib/policy/config/config.go
lib/policy/config/config_test.go
lib/policy/config/testdata/bad/badregexes.json
lib/policy/config/testdata/good/block_cf_workers.json
lib/policy/policy.go
web/index_templ.go

Closes #291 
This adds support for checking headers in bot rules using regular expressions. The most basic rule would look like this:
```json
{
"bots": [
{
"name": "Cloudflare Workers",
"headers_regex": {
"CF-Worker": ".*"
},
"action": "DENY"
}
],
"dnsbl": false
}
```
Each header value is checked against provided expression.
Checklist:

Add headers bot rule

---

.github/workflows/package-builds-stable.yml
.github/workflows/package-builds-unstable.yml

Moves to [TecharoHQ/yeet](https://github.com/TecharoHQ/yeet) for the next release.

chore(ci): migrate to TecharoHQ/yeet

---

docs/docs/user/known-instances.md

Updates the known instances list and add the [NixOS Hydra](https://hydra.nixos.org).

docs(known-instances): add NixOS Hydra

---

docs/docs/admin/environments/nginx.mdx

It would seem the file was originally edited for 2-space indentation but accidentally used tabs instead of actual spaces.
Checklist:

docs: Fix nginx.mdx indentation

---

docs/docs/CHANGELOG.md
docs/docs/admin/policies.mdx
lib/anubis.go
lib/random.go

Previously Anubis would aggressively make sure that the client cookie matched exactly what it should. This has turned out to be too paranoid in practice and has caused problems with Happy Eyeballs et. al.
This is a potential fix to #303 and #289.
Checklist:

fix(lib): make Anubis less paranoid

---

data/botPolicies.json
data/botPolicies.yaml
data/bots/ai-robots-txt.yaml
docs/docs/CHANGELOG.md
lib/policy/checker.go
lib/policy/config/config.go
lib/policy/config/testdata/bad/regex_ends_newline.json
lib/policy/config/testdata/bad/regex_ends_newline.yaml

Closes #372
Fun YAML fact of the day:
What is the difference between how these two expressions are parsed?
```yaml
foo: >
bar
```
```yaml
foo: >-
bar
```
They are invisible in yaml, but when you evaluate them to JSON the difference is obvious:
```json
{
"foo": "bar\n"
}
```
```json
{
"foo": "bar"
}
```
User-Agent strings, URL path values, and HTTP headers _do_ end in newlines in HTTP/1.1 wire form, but that newline is usually stripped before the server actually handles it. Also HTTP/2 is a thing and does not terminate header values with newlines.
This change makes Anubis more aggressively detect mistaken uses of the yaml `>` operator and nudges the user into using the yaml `>-` operator which does not append the trailing newline.
I had honestly forgotten about this YAML behavior because …

fix(config): remove trailing newlines in regexes

---

docs/docs/user/known-instances.md

Just checking bypass-all-shortlinks-debloated and they appeared.

docs(known-instances): add Codeberg

---

README.md

I discovered that your README.md's link to "policies.mdx" didn't work, so I fixed the link.

README.md: Fix link to policy definition docs.

---

docs/docs/user/known-broken-extensions.md

The previous version unnecessarily lowered the protection that JShelter brings to their users. This commits provides three alternatives that users can apply and the recommended one is easier than the original one and less invasive.
I think that you should provide JShelter users with all relevant information.
Checklist (not completed as the change is only in the documentation):

Update information on workarounds for JShelter

---

web/build.sh

fix(web): Avoid timestamping main.mjs.gz

---

.github/workflows/package-builds-stable.yml
.github/workflows/package-builds-unstable.yml
docs/docs/CHANGELOG.md
yeetfile.js

Closes #415
This also bumps yeet to [v0.2.2](https://github.com/TecharoHQ/yeet/releases/tag/v0.2.2) to fix a minor bug with documentation files in the build function being written to the wrong folder.
Checklist:

fix(yeetfile): copy all docs, data files, and botPolicies.yaml

---

cmd/anubis/main.go
docs/docs/CHANGELOG.md

Noticed that Anubis prints something during startup that is not in the JSON format.
I moved the data into the "listening" log message.
Before:
```
Rule error IDs:
* ai-robots-txt: 8e399aa8f9f5d95a8cd0ad01284ea904784a854e9c6ab17ac9994f479d18aaed
* cloudflare-workers: 559e7f01707b78efda8b0ed791e13d0e0079fbf0e3c81c8dfaf2299537f8b666
* lightpanda: 8c4f381bde0fabcd361c88ec7f015d981fd7f80f3edcb16e670ed0bc772eb62d
* headless-chrome: b2dd0d54fa37a160ed04d152bcdde5df296a5861e0a6ef6a4fe845ef51d93be0
* headless-chromium: 900a0b88e9bcd4ae0772b55c198f6fb9e0e352da8af4ed61f7f72df1391f85a2
* us-artificial-intelligence-scraper: 5f0cb91e78d0499d22892c79e1520ccb378e98d3836effbd1ad675721bd46ac1
{"time":"2025-05-01T18:26:37.283704099+03:00","level":"WARN","source":{"function":"main.main","file":"/home/henri/sr …
```

fix(cmd/anubis): print "Rule error IDs" in JSON

---

docs/docs/CHANGELOG.md
xess/xess.css

Rather than prefixing the CSS variables and reproducing most of the styles by media query, we can use the media query to set new values for the CSS variables and simplify the styles.
Checklist:

deduplicate css rules by using media query to set variables

---

docs/docs/admin/environments/apache.mdx

I guess the whole purpose is to avoid having 3001 opened to the world. This is the easyest way to do it (iptables might be an option too)

docs(apache): make listener run on port 3001

---

.github/zizmor.yml

This config silences warnings about Homebrew's actions being unpinned. We don't version those actions, so this will clear up some alerts.

zizmor: add config file to silence unpinned-uses of Homebrew/actions

---

docs/docs/CHANGELOG.md
web/js/main.mjs

A better implementation of #437. This stops the client before proof of work runs.
Checklist:

feat(js): stop execution if the client disabled cookies

---

docs/docs/admin/configuration/subrequest-auth.mdx

* The IP address and Host should be included
* The Content-Length removed to avoid Anubis waiting for the body, which is not passed because subrequest is always using GET.
Checklist:

docs: add missing subrequest auth configuration

---

internal/headers.go
internal/xff_test.go

Fixed X-Forwarded-For parsing bug identified in #455 .
Checklist:

Trim spaces from elements of split XFF string

---

docs/docs/CHANGELOG.md
run/anubis.freebsd

Some changes here to reflect the discussion in pull request 274 regarding the `anubis_env`, `anubis_env_file` and `anubis_args` variables. At the risk of improving personal choices in configuration with a minor amount more complexity, this new script now allows for the use of all three of these, together, with no interference between them all  i.e. 
- if `anubis_env_file` is set, environment variables will be taken from this file
- if `anubis_env` is set, environment variables will be taken from this string of variables, and override matching variables set in `anubis_env_file`
- if `anubis_args` is set, runtime parameters will be taken from this string and override matching ones in both `anubis_env_file` and `anubis_env`
Thanks to @dlangille for the advice with this.
Checklist:

Overhaul anubis.freebsd

---

.github/actions/spelling/expect.txt
docs/docs/CHANGELOG.md
internal/test/playwright_test.go
package.json

This PR allows running the Playwright server in a container, which makes it much easier to run, since it does not depend on the OS having installed some certain libraries or packages.
It uses the official Playwright image like it is explained in the [documentation](https://playwright.dev/docs/docker).
Checklist:

test(playwright): Add Docker and Podman support

---

anubis.go
docs/docs/CHANGELOG.md
lib/anubis.go
lib/anubis_test.go
lib/config.go

Closes #315 
Also properly re-brand the cookies so that some of the /x/ heritage is lost.
Checklist:

fix(lib): use a new cookie per domain when COOKIE_DOMAIN is set

---

docs/docs/CHANGELOG.md
lib/http.go
lib/http_test.go

Previously this made ClearCookie always clear cookies by name even when CookieDomain was set. This change fixes this and adds tests to make sure that this doesn't happen again.
Checklist:

fix(lib): make ClearCookie respect the dynamic cookie name

---

docs/docs/user/known-instances.md

Simply adds https://reddit.nerdvpn.de to the list of known instances in the docs since I saw Anubis there. It might also be used on other services hosted on nerdvpn.de, but I didn't get it to appear anywhere else. There probably is a better way to check that I'm not aware of, so feel free to do that.
Checklist:
The checklist doesn't really apply here, does it? Or are documentation edits also listed in CHANGELOG.md?

Add reddit.nerdvpn.de to known instances

---

docs/docs/CHANGELOG.md
lib/anubis.go
lib/http.go
lib/http_test.go

Closes #520
For some reason, Chrome and Firefox are very picky over what they use to match cookies that need to be deleted. Listen to me for my tale of woe:
The basic problem here is that cookies were an early hack added on the side of the HTTP spec and they're basically impossible to upgrade or change because who knows what relies on the exact behavior cookies use. As a result, cookies don't just match by name, but by every setting that exists on them. You can also have two cookies with the same name but different values. This spec is a nightmare lol.
Even more fun: browsers will make up values for cookies if they aren't set, meaning that getting a challenge token at `/docs` is semantically different than a challenge token you got from `/`.
This PR fixes this issue by explicitly setting …

fix(lib): properly clear out test cookie

---

.github/actions/spelling/expect.txt
docs/docs/admin/native-install.mdx

Using the native-install instructions, default.env was installed as /etc/anubis rather than /etc/anubis/default.env
I created an issue before I decided to just make a PR: #534 
Would you like me to add an entry into the changelog for a typo fix?
Closes #534 
Checklist:

docs: correct the path for the default configuration file

---

.github/actions/spelling/expect.txt
cmd/anubis/main.go
docs/docs/CHANGELOG.md
docs/docs/admin/installation.mdx

When running Anubis in front of a site that's served from a different host, it's nice to be able to specify HTTPS for the `TARGET` and stay end-to-end encrypted.
If that backend server is shared hosting, then the site's own hostname may be the only one that's correct to specify in the TLS handshake (SNI) - but it will be different than the hostname Anubis needs to resolve and connect to.
For example, let's say the site is `site1.example.com` and its backend server is `backend.example.com`. DNS for `site1` points at Anubis, not the backend server. `https://backend.example.com` is the appropriate `TARGET`, but it hosts tons of other sites. If Anubis' handshake and Host header ask for `backend.example.com` it'll serve its default site (wrong), and if Anubis' handshake and Host header …

feat: add TARGET_SNI to allow overriding the TLS handshake hostname when forwarding requests

---

docs/docs/CHANGELOG.md
lib/anubis.go
lib/http.go

Closes #531
This changes `anubis_challenges_issued` to be a vector counter that records the challenge issuance method.
Checklist:

fix(lib): record challenges issused over embedded HTML

---

docs/docs/CHANGELOG.md
lib/anubis.go

For some reason, Google Chrome will randomly send a "full" Accept-Language header, and other times it will send a "partial" Accept-Language header. This makes the challenge construction inconsistent.
This commit fixes this issue by only considering up to the first five characters of the Accept-Language header when making a challenge string.
Checklist:

fix(lib): only use the first five characters of Accept-Language header values

---

lib/anubis.go
lib/anubis_test.go
lib/http.go
lib/testdata/rule_change.yaml

This is an attempt to work around an issue where clients get accepted at one challenge level for one route and then visit a different route at another challenge level without having to pass a challenge again.
Checklist:

feat(lib): annotate cookies with what rule was passed

---

.github/actions/spelling/expect.txt
docs/docs/admin/configuration/subrequest-auth.mdx

Even if totally logical, it caught me by surprise that the subrequest auth configuration by default allows all denied requests.
Checklist:

docs(subrequest-auth): document required policy changes

---

.github/actions/spelling/expect.txt
docs/docs/CHANGELOG.md
web/index.templ
web/index_templ.go

On some browsers with lesser CSS support (UXP browsers like NewMoon), the progress bar is extremely short, because the `min()` function is not supported within the `width` property.
To fix this, without ruining the style for everybody, I've added a simpler `width: 90%;` version over the regular property. **This property will only be used should the browser not support the normal style** -- The second property will override the first, if it is valid to the browser, making it look exactly like before.
It's worth noting that for those browsers in particular (especially NewMoon), the progress bar is important because they tend to be in use by older computers, where the challenge can take multiple minutes (ask my Pentium III).
Checklist:

Make progress bar styling more compatible (UXP, etc)

---

.github/workflows/ssh-ci.yml

This reverts commit 5e95da6b6c820bd12b96e06c732dc9000dbaa81e.
BLOCKED until ppc64le.techaro.lol responds over SSH.

test(ssh-ci): re-enable GOARCH=ppc64le

---

data/botPolicies.yaml
docs/docs/admin/thoth.mdx

There was a typo in example YAML files
Checklist:

fix(geo): correct typo "counties" to "countries"

---

docs/docs/user/known-instances.md

New deployment spotted!
Anubis is currently active on https://extensions.typo3.org.
Checklist:

docs(known-instances): add extensions.typo3.org

---

.github/actions/spelling/expect.txt
data/botPolicies.yaml
docs/docs/CHANGELOG.md
docs/docs/admin/configuration/impressum.mdx
docs/docs/admin/policies.mdx
docs/manifest/cfg/anubis/botPolicies.yaml
lib/challenge/challenge.go
lib/challenge/metarefresh/metarefresh.go
lib/challenge/proofofwork/proofofwork.go
lib/challenge/proofofwork/proofofwork_test.go
lib/config.go
lib/http.go
lib/policy/config/config.go
lib/policy/config/impressum.go
lib/policy/config/impressum_test.go
lib/policy/config/testdata/bad/impressum-no-footer.yaml
lib/policy/config/testdata/bad/impressum-no-page-contents.yaml
lib/policy/config/testdata/good/impressum.yaml
lib/policy/policy.go
web/index.go
web/index.templ
web/index_templ.go

Closes #362 
This lets you customize an imprint/impressum in the bot policy file:
```yaml
impressum:
footer: >-
This website is hosted by Techaro. If you have any complaints or notes 
about the service, please contact
<a href="mailto:contact@techaro.lol">contact@techaro.lol</a> and we
will assist you as soon as possible.
page:
title: Imprint and Privacy Policy
body: >-
<p>Last updated: June 2025</p>
<h2>Information that is gathered from visitors</h2>
<p>In common with other websites, log files are stored on the web server saving details such as the visitor's IP address, browser type, referring page and time of visit.</p>
<p>Cookies may be used to remember visitor preferences when interacting with the website.</p>
<p>Where registration is required, the visitor's email and a username will …
```

feat: implement imprint/impressum support

---

docs/docs/CHANGELOG.md
lib/anubis.go

Closes #564
This one is really dumb. Take a seat and listen to my tale of woe.
While @victorvalenca was working on #693 we ran into a strange issue. The tests would consistently pass on Firefox but instantly failed on Chrome. After adding increasingly desperate debugging logs to the mix, we found out that somehow Chrome was randomizing the contents of its Accept-Language header. This was making the challenge string get calculated differently, thus making things spuriously fail. I cannot figure out what causes Chrome to do this other than you being in an environment where you have more than one "system language" set.
Either way, this should finally fix this issue and bring peace to the land forever*.
Checklist:

fix(lib): fix invalid response after success in Chrome

---

cmd/anubis/main.go
docs/docs/CHANGELOG.md

I see #694 adds both [`Policy.OpenGraph`](https://github.com/TecharoHQ/anubis/pull/694/files#diff-9f6114d273eaabaa7d0da817daa547c05a8209f304129758808b1361c48b1aa9R388) and [`Options.OpenGraph`](https://github.com/TecharoHQ/anubis/pull/694/files#diff-723d6cb1b48895db61a43b5536bffca5ea1157d674fa1ac3903fc3f03addc31cR41). While the configuration is populated in `Policy.OpenGraph`, [it's still `Options.OpenGraph`](https://github.com/TecharoHQ/anubis/pull/694/files#diff-d5149d03328bfe7145aa99f4274ffb678ca26b66293bdcd1342481b5f209246fR83) that is read, which is unfortunately not populated.
Note:
* Maintainers may need to decide whether to use `Policy.OpenGraph` or `Options.OpenGraph`, but I received a report saying my anubis-fronted site lost OpenGraph passthrough, so here is a quick fix for …

Populate OpenGraph configurations to `Options.OpenGraph`

---

docs/docs/admin/environments/apache.mdx

mod_proxy_html is for modifying html content in response bodies. The example configs are using mod_proxy_http.
https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html vs
https://httpd.apache.org/docs/2.4/mod/mod_proxy_http.html
And anyway mod_proxy + mod_proxy_http should already be installed on almost all systems.
Checklist:

remove incorrect module mentions

---

.github/actions/spelling/expect.txt
docs/docs/admin/policies.mdx
lib/store/bbolt/bbolt.go
lib/store/bbolt/bbolt_test.go
lib/store/bbolt/factory.go
lib/store/storetest/storetest.go

[bbolt](https://github.com/etcd-io/bbolt) is a key/value store that supports key groups / buckets. Every key has to be in at least one bucket. Prior to this change, Anubis put each key into the bucket `anubis`. The data and expiry time were wrapped in a JSON object like this:
```json
{
"data": "<b64-encoded bytes>",
"expiry": "<rfc 3339 timestamp>"
}
```
This did work, but it meant that checking the expiry time requires you to unmarshal the entire data packet. The data packet being encoded as base64 also gave a fair amount of overhead, the kind of overhead that simply does not look the best for trying to keep Anubis as fast as humanly possible.
This changes the bbolt flow to create a unique bucket per key/value pair and stores the expiry metadata in another key alongside the data. This …

fix(lib/store/bbolt): use a multi-bucket flow instead of a single bucket flow

---

docs/docs/CHANGELOG.md
internal/thoth/thoth.go

Ref TI-20250709-0001
Checklist:

fix(internal/thoth): don't block Anubis starting if healthcheck fails

---

cmd/anubis/main.go
docs/docs/CHANGELOG.md

This fixes a bug that was introduced in 68b653b0, in which the call to metricsServer was passed a plain context.Background without signal handling.
This commit adds back in the signal handling for the metrics server, as well as for the Thoth client and storage backend.
Closes: #853
Checklist:

fix(cmd/anubis): add signal handling to metrics server

---

docs/docs/CHANGELOG.md
web/js/proof-of-work-slow.mjs
web/js/proof-of-work.mjs

Partial fix #877
In some cases, the parallel solution finder in Anubis could cause all of the worker promises to leak due to the fact the promises were being improperly terminated. A recursion bomb happens in the following scenario:
1. A worker sends a message indicating it found a solution to the proof of work challenge.
2. The `onmessage` handler for that worker calls `terminate()`
3. Inside `terminate()`, the parent process loops through all other workers and calls `w.terminate()` on them.
4. It's possible that terminating a worker could lead to the `onerror` event handler.
5. This would create a recursive loop of `onmessage` -> `terminate` -> `onerror` -> `terminate` -> `onerror` and so on.
This infinite recursion quickly consumes all available stack space, but this has never been …

fix(web): amend future leak on proof of work solution

---

docs/docs/CHANGELOG.md
lib/anubis.go
lib/anubis_test.go

Fixes #869
v1.21.0 changed the core challenge flow to maintain information about challenges on the server side instead of only doing them via stateless idempotent generation functions and relying on details to not change. There was a subtle bug introduced in this change: if a client has an unknown challenge ID set in its test cookie, Anubis will clear that cookie and then throw an HTTP 500 error.
This has been fixed by making Anubis throw a new challenge page instead.
Checklist:

fix(lib): fix challenge issuance logic

---

lib/anubis_test.go
lib/testdata/permissive.yaml

Previously the X-Forwarded-For middleware could return two commas in a row. This is a regression test to make sure that doesn't happen again.
Imports a patch previously exclusive to Botstopper.
Checklist:

test(lib): add a test for the X-Forwarded-For middleware

---

docs/docs/CHANGELOG.md
docs/docs/admin/configuration/expressions.mdx
lib/policy/expressions/environment.go
lib/policy/expressions/environment_test.go

Allows writing rules like this:
```yaml
- name: two-path-segments-no-query
action: ALLOW
expression:
all:
- size(query) == 0
- size(segments(path)) < 2
```
Checklist:

feat(expressions): add segments function to break path into segments

---

docs/docs/CHANGELOG.md

Follows-up 6e4e4717920ab93cfab61e6cde0b0d9a1bacdc8b.

docs: fix "stored" typo in CHANGELOG.md

---

docs/docs/CHANGELOG.md
lib/policy/checker.go
lib/policy/checker_test.go

Implemented the checking of X-Original-URI so that the path rules would work when using it with Subrequest Authentication.
Closes #453
Checklist:

lib/checker: Implement X-Original-URI support

---

cmd/anubis/main.go
docs/docs/CHANGELOG.md

This PR adds the possibility to disable keep-alive to support HTTP backends that do not properly handle it. See https://github.com/TecharoHQ/anubis/issues/1048. This may also be useful for load balancing or load testing.
Checklist:

Allow to disable keep-alive for the targets not supporting it properly

---

docs/docs/CHANGELOG.md
lib/challenge/metarefresh/metarefresh.go

Some admins have noticed that clients are not waiting the right amount of time in order to access a resource protected by the metarefresh challenge. This patch adds a check to make sure that clients have waited at least 95% (difficulty times 950 milliseconds instead of difficulity times 1000 milliseconds) of the time they should.
If this scales, maybe time is the best way to go for Anubis in the near future instead of anything else computational.
Checklist:

fix(challenge/metarefresh): ensure that clients have waited long enough

---

docs/docs/CHANGELOG.md
docs/docs/admin/configuration/expressions.mdx
lib/policy/celchecker.go
lib/policy/expressions/environment.go

feat(expressions): add contentLength to bot expressions

---

anubis.go
docs/docs/CHANGELOG.md

The cookies are named `techaro.lol-anubis-auth-auth` instead of just `techaro.lol-anubis-auth`. This patch fixes that.
Checklist:

fix: mend auth cookie name stutter
